name: Doxygen CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    name: Generate Doxygen Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Vulkan SDK
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: latest
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true


      - name: Setup Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz --no-install-recommends

      - name: Configure CMake with Documentation
        run: |
          cmake -B build -S . -DBUILD_DOCS=ON -DBUILD_FOR_OPENXR=OFF -DBUILD_FOR_GLFW=OFF -DBUILD_TESTING=OFF -DBUILD_EXAMPLES=OFF

      - name: Build Documentation
        run: |
          cmake --build build --target docs

      - name: Save build output
        uses: actions/upload-artifact@v6.0.0
        with:
          name: docs
          path: build/docs/generated-docs/html

  publish:
    if: github.event_name == 'push'
    name: Deploy to GitHub Pages
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          submodules: recursive

      - name: Restore build output
        uses: actions/download-artifact@v7.0.0
        with:
          name: docs
          path: docs/html

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
